# Generated by Django 5.2 on 2025-05-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_remove_profile_experience_remove_profile_job_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='cover_letter',
            new_name='description',
        ),
    ]
