# Generated by Django 5.2 on 2025-05-02 17:59

import job_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0005_profile_description_profile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='description',
            field=models.TextField(blank=True, validators=[job_app.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.CharField(blank=True, max_length=100, validators=[job_app.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='skills',
            field=models.TextField(blank=True, validators=[job_app.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, validators=[job_app.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.TextField(blank=True, validators=[job_app.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, validators=[job_app.models.validate_not_empty]),
        ),
    ]
