# Generated by Django 5.2 on 2025-05-07 17:16

import job_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0006_alter_jobapplication_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_on',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='industry',
            field=models.CharField(blank=True, max_length=100, validators=[job_app.models.validate_not_empty]),
        ),
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.CharField(blank=True, max_length=100, validators=[job_app.models.validate_not_empty]),
        ),
    ]
